FROM node:16-alpine as build

WORKDIR /project

COPY package.json yarn.lock .yarn .yarnrc.yml .
COPY .yarn .yarn
COPY apps/passport/package.json apps/passport/package.json
COPY libs/shared/ libs/shared/

RUN yarn install

COPY apps/passport/ apps/passport/

FROM node:16-alpine as dev

COPY --from="build" /project /project

WORKDIR /project

EXPOSE 3000

CMD [ "yarn", "passport:start" ]
